// /lib/initial-data.ts
// 10 catégories, 10 marques, 10 collections, 10 tags, 10 parfums, 10 flacons

export const INITIAL_CATEGORIES = [
  { id: 'cat-01', name_fr: 'Oud', name_ar: 'عود', slug: 'oud' },
  { id: 'cat-02', name_fr: 'Floral', name_ar: 'زهري', slug: 'floral' },
  { id: 'cat-03', name_fr: 'Oriental', name_ar: 'شرقي', slug: 'oriental' },
  { id: 'cat-04', name_fr: 'Frais', name_ar: 'منعش', slug: 'frais' },
  { id: 'cat-05', name_fr: 'Boisé', name_ar: 'خشبي', slug: 'boise' },
  { id: 'cat-06', name_fr: 'Musqué', name_ar: 'مسكي', slug: 'musque' },
  { id: 'cat-07', name_fr: 'Épicé', name_ar: 'بهاري', slug: 'epice' },
  { id: 'cat-08', name_fr: 'Citrus', name_ar: 'حمضي', slug: 'citrus' },
  { id: 'cat-09', name_fr: 'Aquatique', name_ar: 'مائي', slug: 'aquatique' },
  { id: 'cat-10', name_fr: 'Ambré', name_ar: 'عنبري', slug: 'ambre' },
]

export const INITIAL_BRANDS = [
  { id: 'br-01', name: 'Al Haramain', name_ar: 'الحرمين', logo_url: null, description_fr: 'Maison de parfumerie orientale fondée à La Mecque.' },
  { id: 'br-02', name: 'Amouage', name_ar: 'عمواج', logo_url: null, description_fr: 'La marque de luxe du Sultanat d\'Oman.' },
  { id: 'br-03', name: 'Lattafa', name_ar: 'لطافة', logo_url: null, description_fr: 'Parfums arabes premium accessibles.' },
  { id: 'br-04', name: 'Maison Tahara', name_ar: 'ميزون طهارة', logo_url: null, description_fr: 'Élégance française et âme orientale.' },
  { id: 'br-05', name: 'Rasasi', name_ar: 'رصاصي', logo_url: null, description_fr: 'Parfumerie de Dubaï depuis 1979.' },
  { id: 'br-06', name: 'Swiss Arabian', name_ar: 'سويس عربيان', logo_url: null, description_fr: 'La rencontre de l\'Orient et de l\'Occident.' },
  { id: 'br-07', name: 'Ajmal', name_ar: 'أجمل', logo_url: null, description_fr: 'Une des plus anciennes maisons de parfumerie du Golfe.' },
  { id: 'br-08', name: 'Armaf', name_ar: 'أرماف', logo_url: null, description_fr: 'Parfums de luxe à prix accessible.' },
  { id: 'br-09', name: 'Oud Milano', name_ar: 'عود ميلانو', logo_url: null, description_fr: 'Fusion Orient-Italie, qualité premium.' },
  { id: 'br-10', name: 'Paris Corner', name_ar: 'باريس كورنر', logo_url: null, description_fr: 'Inspirations haute couture françaises.' },
]

export const INITIAL_COLLECTIONS = [
  { id: 'col-01', name_fr: 'Collection Royale', name_ar: 'المجموعة الملكية', description_fr: 'Les essences les plus précieuses, dignes des rois.', cover_url: null },
  { id: 'col-02', name_fr: 'Été Arabe', name_ar: 'الصيف العربي', description_fr: 'Légèreté et fraîcheur pour l\'été.', cover_url: null },
  { id: 'col-03', name_fr: 'Nuit de Sahara', name_ar: 'ليلة الصحراء', description_fr: 'Profondeur et mystère du désert.', cover_url: null },
  { id: 'col-04', name_fr: 'Prestige', name_ar: 'بريستيج', description_fr: 'Notre sélection premium.', cover_url: null },
  { id: 'col-05', name_fr: 'Bakhoor Heritage', name_ar: 'تراث البخور', description_fr: 'L\'art ancestral du bakhoor.', cover_url: null },
  { id: 'col-06', name_fr: 'Oud Signature', name_ar: 'توقيع العود', description_fr: 'La quintessence de l\'oud.', cover_url: null },
  { id: 'col-07', name_fr: 'Fleurs d\'Orient', name_ar: 'أزهار الشرق', description_fr: 'Les fleurs rares de la péninsule arabique.', cover_url: null },
  { id: 'col-08', name_fr: 'Masculin Intense', name_ar: 'رجولي مكثف', description_fr: 'Compositions intenses pour homme.', cover_url: null },
  { id: 'col-09', name_fr: 'Féminité Dorée', name_ar: 'أنوثة ذهبية', description_fr: 'Douceur, fleur et musc pour elle.', cover_url: null },
  { id: 'col-10', name_fr: 'Zen & Méditation', name_ar: 'زن وتأمل', description_fr: 'Sérénité et notes apaisantes.', cover_url: null },
]

export const INITIAL_TAGS = [
  { id: 'tag-01', name_fr: 'Arrivage', name_ar: 'وصل جديد', slug: 'arrivage', show_on_homepage: true, homepage_order: 1 },
  { id: 'tag-02', name_fr: 'Best-seller', name_ar: 'الأكثر مبيعاً', slug: 'best-seller', show_on_homepage: true, homepage_order: 2 },
  { id: 'tag-03', name_fr: 'Premium', name_ar: 'مميز', slug: 'premium', show_on_homepage: true, homepage_order: 3 },
  { id: 'tag-04', name_fr: 'Offre spéciale', name_ar: 'عرض خاص', slug: 'offre-speciale', show_on_homepage: false, homepage_order: 4 },
  { id: 'tag-05', name_fr: 'Exclusif', name_ar: 'حصري', slug: 'exclusif', show_on_homepage: false, homepage_order: 5 },
  { id: 'tag-06', name_fr: 'Saisonnier', name_ar: 'موسمي', slug: 'saisonnier', show_on_homepage: false, homepage_order: 6 },
  { id: 'tag-07', name_fr: 'Coup de cœur', name_ar: 'المفضل', slug: 'coup-de-coeur', show_on_homepage: false, homepage_order: 7 },
  { id: 'tag-08', name_fr: 'Nouveauté', name_ar: 'جديد', slug: 'nouveaute', show_on_homepage: false, homepage_order: 8 },
  { id: 'tag-09', name_fr: 'Limité', name_ar: 'محدود', slug: 'limite', show_on_homepage: false, homepage_order: 9 },
  { id: 'tag-10', name_fr: 'Professionnel', name_ar: 'مهني', slug: 'professionnel', show_on_homepage: false, homepage_order: 10 },
]

export const INITIAL_PRODUCTS = [
  // 10 PARFUMS
  {
    id: 'prf-01', product_type: 'perfume' as const,
    name_fr: 'Rose du Taif', name_ar: 'وردة الطائف', slug: 'rose-du-taif',
    description_fr: 'Une huile de parfum envoûtante aux notes de rose de Taïf, oud blanc et musc rare.',
    description_ar: 'زيت عطري فاتن بنفحات وردة الطائف والعود الأبيض والمسك النادر.',
    category_id: 'cat-02', brand_id: 'br-01', collection_id: 'col-07',
    tag_ids: ['tag-01', 'tag-02'], price_per_gram: 850, stock_grams: 5000,
    images: ['/images/products/rose-du-taif.png'], status: 'active' as const, created_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'prf-02', product_type: 'perfume' as const,
    name_fr: 'Oud Malaki', name_ar: 'عود ملكي', slug: 'oud-malaki',
    description_fr: 'L\'oud royal dans toute sa splendeur. Profond, chaleureux, impérial.',
    description_ar: 'العود الملكي في كامل روعته. عميق، دافئ، فاخر.',
    category_id: 'cat-01', brand_id: 'br-02', collection_id: 'col-01',
    tag_ids: ['tag-02', 'tag-03'], price_per_gram: 1200, stock_grams: 3000,
    images: ['/images/products/oud-malaki.png'], status: 'active' as const, created_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'prf-03', product_type: 'perfume' as const,
    name_fr: 'Jasmin Sauvage', name_ar: 'ياسمين بري', slug: 'jasmin-sauvage',
    description_fr: 'Jasmin blanc intense capturé à l\'aurore. Frais, floral, addictif.',
    description_ar: 'ياسمين أبيض مكثف يُقطف عند الفجر. منعش، زهري، مُدمِن.',
    category_id: 'cat-02', brand_id: 'br-04', collection_id: 'col-02',
    tag_ids: ['tag-01'], price_per_gram: 650, stock_grams: 4500,
    images: ['/images/products/jasmin-sauvage.png'], status: 'active' as const, created_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 'prf-04', product_type: 'perfume' as const,
    name_fr: 'Ambre Noir', name_ar: 'عنبر أسود', slug: 'ambre-noir',
    description_fr: 'Un ambre mystérieux aux accords de bois précieux et vanille noire.',
    description_ar: 'عنبر غامض بمزيج الأخشاب النفيسة والفانيلا السوداء.',
    category_id: 'cat-10', brand_id: 'br-05', collection_id: 'col-03',
    tag_ids: ['tag-03'], price_per_gram: 950, stock_grams: 2500,
    images: ['/images/products/ambre-noir.png'], status: 'active' as const, created_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 'prf-05', product_type: 'perfume' as const,
    name_fr: 'Musc Tahara', name_ar: 'مسك طهارة', slug: 'musc-tahara',
    description_fr: 'Musc blanc pur, délicat et soyeux. Une pureté absolue.',
    description_ar: 'مسك أبيض نقي، رقيق وحريري. نقاء مطلق.',
    category_id: 'cat-06', brand_id: 'br-04', collection_id: 'col-04',
    tag_ids: ['tag-01', 'tag-02'], price_per_gram: 500, stock_grams: 6000,
    images: ['/images/products/musc-tahara.png'], status: 'active' as const, created_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 'prf-06', product_type: 'perfume' as const,
    name_fr: 'Bakhoor Al Majd', name_ar: 'بخور المجد', slug: 'bakhoor-al-majd',
    description_fr: 'L\'essence du bakhoor traditionnel en huile concentrée.',
    description_ar: 'جوهر البخور التقليدي في زيت مركّز. رحلة إلى قلب الشرق.',
    category_id: 'cat-01', brand_id: 'br-01', collection_id: 'col-05',
    tag_ids: ['tag-03'], price_per_gram: 1100, stock_grams: 2000,
    images: ['/images/products/bakhoor-al-majd.png'], status: 'active' as const, created_at: '2026-02-20T10:00:00Z',
  },
  {
    id: 'prf-07', product_type: 'perfume' as const,
    name_fr: 'Cedar & Iris', name_ar: 'سيدار وإيريس', slug: 'cedar-iris',
    description_fr: 'Cèdre du Liban et iris poudré. Élégance boisée intemporelle.',
    description_ar: 'أرز لبنان والإيريس المسحوق. أناقة خشبية خالدة.',
    category_id: 'cat-05', brand_id: 'br-06', collection_id: 'col-04',
    tag_ids: ['tag-02'], price_per_gram: 780, stock_grams: 3500,
    images: ['https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=1000&auto=format&fit=crop'], status: 'active' as const, created_at: '2026-03-01T10:00:00Z',
  },
  {
    id: 'prf-08', product_type: 'perfume' as const,
    name_fr: 'Nuit Orientale', name_ar: 'ليلة شرقية', slug: 'nuit-orientale',
    description_fr: 'Épices chaudes, santal et oud fumé pour les nuits d\'exception.',
    description_ar: 'توابل دافئة وصندل وعود مدخن لليالي الاستثنائية.',
    category_id: 'cat-03', brand_id: 'br-03', collection_id: 'col-03',
    tag_ids: ['tag-01', 'tag-03'], price_per_gram: 1050, stock_grams: 1800,
    images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1000&auto=format&fit=crop'], status: 'active' as const, created_at: '2026-03-05T10:00:00Z',
  },
  {
    id: 'prf-09', product_type: 'perfume' as const,
    name_fr: 'Patchouli Royal', name_ar: 'باتشولي ملكي', slug: 'patchouli-royal',
    description_fr: 'Patchouli sombre, cuir et vanille. Un sillage de prestige.',
    description_ar: 'باتشولي داكن، جلد وفانيلا. أثر رائحة يستحق الملوك.',
    category_id: 'cat-07', brand_id: 'br-07', collection_id: 'col-01',
    tag_ids: ['tag-02', 'tag-03'], price_per_gram: 920, stock_grams: 2800,
    images: ['https://images.unsplash.com/photo-1557170334-a9632e77c6e4?q=80&w=1000&auto=format&fit=crop'], status: 'active' as const, created_at: '2026-03-10T10:00:00Z',
  },
  {
    id: 'prf-10', product_type: 'perfume' as const,
    name_fr: 'Aqua Zafira', name_ar: 'أكوا زافيرة', slug: 'aqua-zafira',
    description_fr: 'Notes marines, bergamote et muscs blancs. Fraîcheur méditerranéenne.',
    description_ar: 'نفحات بحرية وبرغموت ومسك أبيض. انتعاش البحر الأبيض المتوسط.',
    category_id: 'cat-09', brand_id: 'br-10', collection_id: 'col-02',
    tag_ids: ['tag-01'], price_per_gram: 580, stock_grams: 4000,
    images: ['https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=1000&auto=format&fit=crop'], status: 'active' as const, created_at: '2026-03-15T10:00:00Z',
  },
  // 10 FLACONS
  {
    id: 'flc-01', product_type: 'flacon' as const,
    name_fr: 'Flacon Classique Transparent', name_ar: 'قارورة كلاسيكية شفافة', slug: 'flacon-classique',
    description_fr: 'Flacon en verre épais, bouchon doré. Design intemporel.',
    description_ar: 'قارورة زجاج سميك، سدادة ذهبية. تصميم خالد وأنيق.',
    category_id: 'cat-01', brand_id: null, collection_id: null,
    tag_ids: ['tag-01'],
    base_price: 350, images: ['https://images.unsplash.com/photo-1512203530485-2bc305397457?q=80&w=1000&auto=format&fit=crop'], status: 'active' as const, created_at: '2026-01-10T10:00:00Z',
    variants: [
      { id: 'fv-001', size_ml: 30, color: '#F8F8FF', color_name: 'Transparent', shape: 'Carré', price: 350, stock_units: 200 },
      { id: 'fv-002', size_ml: 50, color: '#F8F8FF', color_name: 'Transparent', shape: 'Carré', price: 450, stock_units: 150 },
      { id: 'fv-003', size_ml: 100, color: '#F8F8FF', color_name: 'Transparent', shape: 'Carré', price: 600, stock_units: 100 },
    ],
  },
  {
    id: 'flc-02', product_type: 'flacon' as const,
    name_fr: 'Flacon Luxe Noir Atomiseur', name_ar: 'قارورة فخمة سوداء بخاخ', slug: 'flacon-noir-atomiseur',
    description_fr: 'Verre teinté noir mat avec atomiseur doré. L\'élégance absolue.',
    description_ar: 'زجاج ملون بالأسود المات مع بخاخ ذهبي. الأناقة المطلقة.',
    category_id: 'cat-01', brand_id: null, collection_id: null,
    tag_ids: ['tag-02', 'tag-03'],
    base_price: 550, images: ['https://images.unsplash.com/photo-1627384113743-6bd5a479fffd?q=80&w=1000&auto=format&fit=crop'], status: 'active' as const, created_at: '2026-01-12T10:00:00Z',
    variants: [
      { id: 'fv-004', size_ml: 30, color: '#1A1A1A', color_name: 'Noir Mat', shape: 'Rond', price: 550, stock_units: 80 },
      { id: 'fv-005', size_ml: 50, color: '#1A1A1A', color_name: 'Noir Mat', shape: 'Rond', price: 750, stock_units: 60 },
      { id: 'fv-006', size_ml: 100, color: '#1A1A1A', color_name: 'Noir Mat', shape: 'Rond', price: 950, stock_units: 40 },
      { id: 'fv-007', size_ml: 50, color: '#1B2A4A', color_name: 'Bleu Nuit', shape: 'Rond', price: 780, stock_units: 35 },
    ],
  },
  {
    id: 'flc-03', product_type: 'flacon' as const,
    name_fr: 'Flacon Oriental Gravé', name_ar: 'قارورة شرقية منقوشة', slug: 'flacon-oriental-grave',
    description_fr: 'Verre épais avec motifs orientaux gravés. Bouchon métal doré ciselé.',
    description_ar: 'زجاج سميك بنقوش شرقية. سدادة معدنية ذهبية منحوتة.',
    category_id: 'cat-01', brand_id: null, collection_id: null,
    tag_ids: ['tag-03'],
    base_price: 890, images: ['https://images.unsplash.com/photo-1583445013765-48c218c21a4f?q=80&w=1000&auto=format&fit=crop'], status: 'active' as const, created_at: '2026-01-18T10:00:00Z',
    variants: [
      { id: 'fv-008', size_ml: 50, color: '#C9A84C', color_name: 'Or Ambré', shape: 'Octogonal', price: 890, stock_units: 50 },
      { id: 'fv-009', size_ml: 100, color: '#C9A84C', color_name: 'Or Ambré', shape: 'Octogonal', price: 1200, stock_units: 30 },
      { id: 'fv-010', size_ml: 50, color: '#1B4332', color_name: 'Vert Émeraude', shape: 'Octogonal', price: 920, stock_units: 45 },
      { id: 'fv-011', size_ml: 100, color: '#1B4332', color_name: 'Vert Émeraude', shape: 'Octogonal', price: 1250, stock_units: 25 },
    ],
  },
  {
    id: 'flc-04', product_type: 'flacon' as const,
    name_fr: 'Mini Flacon Voyage', name_ar: 'قارورة ميني للسفر', slug: 'mini-flacon-voyage',
    description_fr: 'Format de voyage pratique, parfait pour les petites commandes.',
    description_ar: 'حجم سفر عملي، مثالي للطلبات الصغيرة أو الهدايا.',
    category_id: 'cat-01', brand_id: null, collection_id: null,
    tag_ids: ['tag-01', 'tag-02'],
    base_price: 180, images: ['https://images.unsplash.com/photo-1615484477778-ca3b77940c25?q=80&w=1000&auto=format&fit=crop'], status: 'active' as const, created_at: '2026-01-25T10:00:00Z',
    variants: [
      { id: 'fv-012', size_ml: 5, color: '#F8F8FF', color_name: 'Transparent', shape: 'Cylindrique', price: 180, stock_units: 500 },
      { id: 'fv-013', size_ml: 10, color: '#F8F8FF', color_name: 'Transparent', shape: 'Cylindrique', price: 220, stock_units: 400 },
      { id: 'fv-014', size_ml: 5, color: '#E8D5B7', color_name: 'Beige Doré', shape: 'Cylindrique', price: 200, stock_units: 300 },
    ],
  },
  {
    id: 'flc-05', product_type: 'flacon' as const,
    name_fr: 'Flacon Carré Élégant', name_ar: 'قارورة مربعة أنيقة', slug: 'flacon-carre-elegant',
    description_fr: 'Design géométrique épuré. Disponible en plusieurs coloris.',
    description_ar: 'تصميم هندسي راقٍ. متوفر بعدة ألوان عصرية.',
    category_id: 'cat-01', brand_id: null, collection_id: null,
    tag_ids: ['tag-02'],
    base_price: 420, images: ['https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=1000&auto=format&fit=crop'], status: 'active' as const, created_at: '2026-02-05T10:00:00Z',
    variants: [
      { id: 'fv-015', size_ml: 30, color: '#FFFFFF', color_name: 'Blanc', shape: 'Carré', price: 420, stock_units: 120 },
      { id: 'fv-016', size_ml: 50, color: '#FFFFFF', color_name: 'Blanc', shape: 'Carré', price: 520, stock_units: 100 },
      { id: 'fv-017', size_ml: 30, color: '#8B4513', color_name: 'Marron Boisé', shape: 'Carré', price: 440, stock_units: 80 },
      { id: 'fv-018', size_ml: 50, color: '#8B4513', color_name: 'Marron Boisé', shape: 'Carré', price: 540, stock_units: 60 },
      { id: 'fv-019', size_ml: 30, color: '#2C3E50', color_name: 'Ardoise', shape: 'Carré', price: 450, stock_units: 70 },
    ],
  },
  {
    id: 'flc-06', product_type: 'flacon' as const,
    name_fr: 'Flacon Goutte Arabesque', name_ar: 'قارورة قطرة عربسك', slug: 'flacon-goutte-arabesque',
    description_fr: 'Forme goutte avec motifs arabesques, inspiration orientale pure.',
    description_ar: 'شكل قطرة بنقوش أرابيسك، إلهام شرقي أصيل.',
    category_id: 'cat-01', brand_id: null, collection_id: null,
    tag_ids: ['tag-03', 'tag-01'],
    base_price: 720, images: [], status: 'active' as const, created_at: '2026-02-12T10:00:00Z',
    variants: [
      { id: 'fv-020', size_ml: 50, color: '#C9A84C', color_name: 'Or', shape: 'Goutte', price: 720, stock_units: 45 },
      { id: 'fv-021', size_ml: 100, color: '#C9A84C', color_name: 'Or', shape: 'Goutte', price: 980, stock_units: 30 },
      { id: 'fv-022', size_ml: 50, color: '#B22222', color_name: 'Rouge Rubis', shape: 'Goutte', price: 750, stock_units: 40 },
      { id: 'fv-023', size_ml: 50, color: '#1B4332', color_name: 'Émeraude', shape: 'Goutte', price: 750, stock_units: 35 },
    ],
  },
  {
    id: 'flc-07', product_type: 'flacon' as const,
    name_fr: 'Flacon Roll-on Pratique', name_ar: 'قارورة رول أون عملية', slug: 'flacon-roll-on',
    description_fr: 'Roll-on en verre pour application directe. Idéal pour les huiles.',
    description_ar: 'رول أون زجاجي للتطبيق المباشر. مثالي لزيوت العطور.',
    category_id: 'cat-01', brand_id: null, collection_id: null,
    tag_ids: ['tag-01', 'tag-02'],
    base_price: 150, images: [], status: 'active' as const, created_at: '2026-02-18T10:00:00Z',
    variants: [
      { id: 'fv-024', size_ml: 6, color: '#F8F8FF', color_name: 'Transparent', shape: 'Roll-on', price: 150, stock_units: 600 },
      { id: 'fv-025', size_ml: 10, color: '#F8F8FF', color_name: 'Transparent', shape: 'Roll-on', price: 190, stock_units: 500 },
      { id: 'fv-026', size_ml: 6, color: '#1A1A1A', color_name: 'Noir', shape: 'Roll-on', price: 165, stock_units: 400 },
    ],
  },
  {
    id: 'flc-08', product_type: 'flacon' as const,
    name_fr: 'Flacon Prestige Grande Capacité', name_ar: 'قارورة بريستيج كبيرة', slug: 'flacon-prestige',
    description_fr: 'Pour les professionnels exigeants. Verre épais, bouchon métal luxueux.',
    description_ar: 'للمحترفين المتطلبين. زجاج سميك، سدادة معدنية فاخرة.',
    category_id: 'cat-01', brand_id: null, collection_id: null,
    tag_ids: ['tag-03'],
    base_price: 1100, images: [], status: 'active' as const, created_at: '2026-03-02T10:00:00Z',
    variants: [
      { id: 'fv-027', size_ml: 100, color: '#F8F8FF', color_name: 'Cristal', shape: 'Carré Biseauté', price: 1100, stock_units: 25 },
      { id: 'fv-028', size_ml: 200, color: '#F8F8FF', color_name: 'Cristal', shape: 'Carré Biseauté', price: 1800, stock_units: 15 },
      { id: 'fv-029', size_ml: 100, color: '#1A1A1A', color_name: 'Noir Brillant', shape: 'Carré Biseauté', price: 1150, stock_units: 20 },
    ],
  },
  {
    id: 'flc-09', product_type: 'flacon' as const,
    name_fr: 'Flacon Bohème Coloré', name_ar: 'قارورة بوهيم ملونة', slug: 'flacon-boheme',
    description_fr: 'Verre coloré artisanal, chaque pièce est unique. Style bohème chic.',
    description_ar: 'زجاج ملون حرفي، كل قطعة فريدة. أسلوب بوهيمي راقٍ.',
    category_id: 'cat-01', brand_id: null, collection_id: null,
    tag_ids: ['tag-01'],
    base_price: 480, images: [], status: 'active' as const, created_at: '2026-03-08T10:00:00Z',
    variants: [
      { id: 'fv-030', size_ml: 30, color: '#8B0000', color_name: 'Rouge Bordeaux', shape: 'Irrégulier', price: 480, stock_units: 60 },
      { id: 'fv-031', size_ml: 30, color: '#00695C', color_name: 'Vert Forêt', shape: 'Irrégulier', price: 490, stock_units: 55 },
      { id: 'fv-032', size_ml: 30, color: '#4A0080', color_name: 'Violet Royal', shape: 'Irrégulier', price: 490, stock_units: 50 },
      { id: 'fv-033', size_ml: 50, color: '#C9A84C', color_name: 'Or Antique', shape: 'Irrégulier', price: 620, stock_units: 40 },
    ],
  },
  {
    id: 'flc-10', product_type: 'flacon' as const,
    name_fr: 'Flacon Hexagonal Premium', name_ar: 'قارورة سداسية بريميوم', slug: 'flacon-hexagonal',
    description_fr: 'Forme hexagonale géométrique, verre épais taillé. Classe absolue.',
    description_ar: 'شكل سداسي هندسي، زجاج سميك مصقول. أناقة فائقة.',
    category_id: 'cat-01', brand_id: null, collection_id: null,
    tag_ids: ['tag-02', 'tag-03'],
    base_price: 680, images: [], status: 'active' as const, created_at: '2026-03-12T10:00:00Z',
    variants: [
      { id: 'fv-034', size_ml: 50, color: '#F8F8FF', color_name: 'Cristal', shape: 'Hexagonal', price: 680, stock_units: 70 },
      { id: 'fv-035', size_ml: 100, color: '#F8F8FF', color_name: 'Cristal', shape: 'Hexagonal', price: 950, stock_units: 50 },
      { id: 'fv-036', size_ml: 50, color: '#1A1A1A', color_name: 'Noir Intense', shape: 'Hexagonal', price: 710, stock_units: 40 },
      { id: 'fv-037', size_ml: 100, color: '#1A1A1A', color_name: 'Noir Intense', shape: 'Hexagonal', price: 980, stock_units: 30 },
    ],
  },
]

export const INITIAL_ANNOUNCEMENTS = [
  { id: 'ann-01', text_fr: 'Livraison gratuite pour les commandes de plus de 50 000 DZD', text_ar: 'توصيل مجاني للطلبات فوق 50,000 دج', is_active: true, display_order: 1 },
  { id: 'ann-02', text_fr: 'Nouveaux arrivages de flacons de luxe disponibles', text_ar: 'وصلت قوارير فاخرة جديدة', is_active: true, display_order: 2 },
  { id: 'ann-03', text_fr: 'Paiement à la livraison dans toutes les 58 wilayas', text_ar: 'الدفع عند الاستلام في جميع الولايات الـ58', is_active: true, display_order: 3 },
]
