export const wilayas = [
  { id: "1", name: "Adrar", nameAR: "أدرار" },
  { id: "2", name: "Chlef", nameAR: "الشلف" },
  { id: "3", name: "Laghouat", nameAR: "الأغواط" },
  { id: "4", name: "Oum El Bouaghi", nameAR: "أم البواقي" },
  { id: "5", name: "Batna", nameAR: "باتنة" },
  { id: "6", name: "Béjaïa", nameAR: "بجاية" },
  { id: "7", name: "Biskra", nameAR: "بسكرة" },
  { id: "8", name: "Béchar", nameAR: "بشار" },
  { id: "9", name: "Blida", nameAR: "البليدة" },
  { id: "10", name: "Bouira", nameAR: "البويرة" },
  { id: "11", name: "Tamanrasset", nameAR: "تمنراست" },
  { id: "12", name: "Tébessa", nameAR: "تبسة" },
  { id: "13", name: "Tlemcen", nameAR: "تلمسان" },
  { id: "14", name: "Tiaret", nameAR: "تيارت" },
  { id: "15", name: "Tizi Ouzou", nameAR: "تيزي وزو" },
  { id: "16", name: "Alger", nameAR: "الجزائر" },
  { id: "17", name: "Djelfa", nameAR: "الجلفة" },
  { id: "18", name: "Jijel", nameAR: "جيجل" },
  { id: "19", name: "Sétif", nameAR: "سطيف" },
  { id: "20", name: "Saïda", nameAR: "سعيدة" },
  { id: "21", name: "Skikda", nameAR: "سكيكدة" },
  { id: "22", name: "Sidi Bel Abbès", nameAR: "سيدي بلعباس" },
  { id: "23", name: "Annaba", nameAR: "عنابة" },
  { id: "24", name: "Guelma", nameAR: "قالمة" },
  { id: "25", name: "Constantine", nameAR: "قسنطينة" },
  { id: "26", name: "Médéa", nameAR: "المدية" },
  { id: "27", name: "Mostaganem", nameAR: "مستغانم" },
  { id: "28", name: "M'Sila", nameAR: "المسيلة" },
  { id: "29", name: "Mascara", nameAR: "معسكر" },
  { id: "30", name: "Ouargla", nameAR: "ورقلة" },
  { id: "31", name: "Oran", nameAR: "وهران" },
  { id: "32", name: "El Bayadh", nameAR: "البيض" },
  { id: "33", name: "Illizi", nameAR: "إيليزي" },
  { id: "34", name: "Bordj Bou Arreridj", nameAR: "برج بوعريريج" },
  { id: "35", name: "Boumerdès", nameAR: "بومرداس" },
  { id: "36", name: "El Tarf", nameAR: "الطارف" },
  { id: "37", name: "Tindouf", nameAR: "تندوف" },
  { id: "38", name: "Tissemsilt", nameAR: "تيسمسيلت" },
  { id: "39", name: "El Oued", nameAR: "الوادي" },
  { id: "40", name: "Khenchela", nameAR: "خنشلة" },
  { id: "41", name: "Souk Ahras", nameAR: "سوق أهراس" },
  { id: "42", name: "Tipaza", nameAR: "تيبازة" },
  { id: "43", name: "Mila", nameAR: "ميلة" },
  { id: "44", name: "Aïn Defla", nameAR: "عين الدفلى" },
  { id: "45", name: "Naâma", nameAR: "النعامة" },
  { id: "46", name: "Aïn Témouchent", nameAR: "عين تموشنت" },
  { id: "47", name: "Ghardaïa", nameAR: "غرداية" },
  { id: "48", name: "Relizane", nameAR: "غليزان" },
  { id: "49", name: "Timimoun", nameAR: "تيميمون" },
  { id: "50", name: "Bordj Badji Mokhtar", nameAR: "برج باجي مختار" },
  { id: "51", name: "Ouled Djellal", nameAR: "أولاد جلال" },
  { id: "52", name: "Béni Abbès", nameAR: "بني عباس" },
  { id: "53", name: "In Salah", nameAR: "عين صالح" },
  { id: "54", name: "In Guezzam", nameAR: "عين قزام" },
  { id: "55", name: "Touggourt", nameAR: "تقرت" },
  { id: "56", name: "Djanet", nameAR: "جانت" },
  { id: "57", name: "El M'Ghair", nameAR: "المغير" },
  { id: "58", name: "El Meniaa", nameAR: "المنيعة" }
];
